In [1]:
# importing numpy
import numpy as np

In [ ]:
arr = [4,8,5,2,3,6,9,7,4,1,5,2,4,9,1,55,4,7]
for i in range(len(arr)):
    if arr[1] == 8:
        print("8 is at:")

ARRAY CREATION

In [2]:
# passing list as array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
# passing tuple as array
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
# 1-D array
arr = np.array([19])
print(arr)

[19]


In [6]:
# 2-D arrays
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3-D arrays
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# 'ndim' to find dimension of array
arr = np.array([[1,2,3], [4,5,6]])
print(arr.ndim)

2


In [9]:
# 'ndmin' to define dimensions of array
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


ARRAY INDEXING

In [11]:
# accessing elements by index number
arr = np.array([1,2,3,4,5,6])
print("First element: ", arr[0])
print("Third element: ", arr[2])

First element:  1
Third element:  3


In [12]:
# adding elements of araay using index number
print("Sum of first and last element: ", arr[0]+arr[-1])

Sum of first and last element:  7


In [13]:
# accessing elements in 2-D array
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print("Second element of second row: ", arr[1,1])

[[1 2 3]
 [4 5 6]]
Second element of second row:  5


In [15]:
# accessing elements in 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


ARRAY SLICING

In [16]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])

[2 3 4]


In [17]:
print(arr[:3])

[1 2 3]


In [18]:
print(arr[4:])

[5 6 7]


In [21]:
print(arr[0:6:2])

[1 3 5]


In [24]:
print(arr[-3:-1])

[5 6]


In [26]:
print(arr[::2])

[1 3 5 7]


In [27]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr[1, :1])

[4]


In [28]:
print(arr[0, :2])

[1 2]


In [30]:
print(arr[0:2, 2]) # from both arrays return third element

[3 6]


DATATYPES IN NumPy

In [32]:
# checking datatype of array
arr = np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [34]:
arr = np.array(["a", "b"])
print(arr)
print(arr.dtype)

['a' 'b']
<U1


In [36]:
# definig datatype of array
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [38]:
# using astype() to define datatype
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
new = arr.astype('S')
print(new)

[1 2 3 4 5]
int64
[b'1' b'2' b'3' b'4' b'5']


COPY VS VIEW

In [39]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [41]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# base to check whether array owns the data or not
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


ARRAY OPERATIONS

In [43]:
# shape of array
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [45]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4 5]]]]]
shape of array : (1, 1, 1, 1, 5)


In [47]:
# reshaping
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr.reshape(2,4))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [48]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(arr.reshape(2,3,2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [50]:
# use of unknown dimensions
print(arr.reshape(2,3,-1))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
# flattening an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [52]:
print(arr.flatten(order='C'))
print(arr.flatten(order='F'))

[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [57]:
print(arr.ravel())

[1 2 3 4 5 6]


In [59]:
print(arr)
print(np.rot90(arr, k=1))

[[1 2 3]
 [4 5 6]]
[[3 6]
 [2 5]
 [1 4]]


In [60]:
print(np.flip(arr, axis=0))

[[4 5 6]
 [1 2 3]]


In [61]:
print(np.fliplr(arr))

[[3 2 1]
 [6 5 4]]


ARRAY ITERATION

In [62]:
# iteration using for loops
arr = np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [64]:
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [65]:
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


In [66]:
# using nditer()
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [67]:
# using buffer space and changing datatypes while iterating
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [68]:
# iteration using step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [69]:
# ndenumerate() 
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [70]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


JOINING ARRAYS

In [71]:
# concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [74]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [78]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [75]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [77]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


SPLITTING ARRAYS

In [79]:
# array_split()
arr = np.array([1,2,3,4,5,6])
a = np.array_split(arr, 3)
print(a)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [80]:
arr = np.array([1,2,3,4,5,6])
a = np.array_split(arr, 4)
print(a)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [81]:
arr = np.array([1,2,3,4,5,6])
a = np.array_split(arr, 3)
print(a[0])
print(a[1])
print(a[2])

[1 2]
[3 4]
[5 6]


In [82]:
arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
a = np.array_split(arr, 3)
print(a)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [83]:
arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
a = np.array_split(arr, 3, axis=1)
print(a)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


In [85]:
arr = np.array([[1,2], [3,4], [5,6], [7,8]])
a = np.hsplit(arr, 2)
print(a)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


SEARCHING ARRAYS

In [87]:
# where()
arr = np.array([1,2,3,4,5])
print(np.where(arr == 4))

(array([3]),)


In [88]:
print(np.where(arr % 2 == 0))

(array([1, 3]),)


In [89]:
# searchsorted()
arr = np.array([5,6,7,8,9])
print(np.searchsorted(arr, 8))

3


In [90]:
arr = np.array([5,6,7,8,9])
print(np.searchsorted(arr, 8, side = 'right'))

4


In [92]:
arr = np.array([1,3,5,7])
print(np.searchsorted(arr, [2,4,6]))

[1 2 3]


SORTING ARRAYS

In [93]:
arr = np.array([3,7,2,4])
print(np.sort(arr))

[2 3 4 7]


In [94]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [95]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [96]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


FILTERING ARRAYS

In [97]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [100]:
# creating filter array
arr = np.array([41, 42, 43, 44])
filter_arr = []
for x in arr:
  if x > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [101]:
# creating filter directly from array
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


ARRAY BROADCASTING

In [102]:
a = np.array([1, 2, 3])
print(a + 5)

[6 7 8]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10,20,30])
print(a + b)

[[11 22 33]
 [14 25 36]]


In [104]:
a = np.array([[1], [2], [3]])
b = np.array([10,20,30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


MATHEMATICAL FUNCTIONS

In [106]:
# arithmetic operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, 2))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [108]:
# trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
# exponential and logarithmic functions
x = np.array([1, 2, 3])
print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.sqrt(x))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[1.         1.41421356 1.73205081]


In [113]:
# statistical functions
a = np.array([[1,2,3], [4,5,6]])
print(np.mean(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.sum(a, axis=0))  # column-wise sum
print(np.sum(a, axis=1))  # row-wise sum


3.5
21
1
6
1.707825127659933
[5 7 9]
[ 6 15]


In [116]:
# comparison functions
a = np.array([1, 2, 3])
print(np.greater(a, 2))

[False False  True]


In [117]:
# boolean and logical functions
a = np.array([True, False, True])
b = np.array([False, False, True])

print(np.logical_and(a, b))
print(np.logical_or(a, b))
print(np.logical_not(a))

[False False  True]
[ True False  True]
[False  True False]


In [118]:
# universal functions
a = np.array([-2.7, -1.5, -0.2, 0.2, 1.5, 2.7])
print("abs   :", np.abs(a))             # distance from 0
print("round :", np.round(a))           # nearest integer
print("floor :", np.floor(a))           # rounds downward
print("ceil  :", np.ceil(a))            # rounds upward

abs   : [2.7 1.5 0.2 0.2 1.5 2.7]
round : [-3. -2. -0.  0.  2.  3.]
floor : [-3. -2. -1.  0.  1.  2.]
ceil  : [-2. -1. -0.  1.  2.  3.]
